# Generated by Django 2.2.16 on 2020-10-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_hjhkh'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='jjhkjh',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
